"""rename wishlist to favorite

Revision ID: 235d3e9b9fc2
Revises: 696a56e8234a
Create Date: 2026-06-16 10:56:39.572920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '235d3e9b9fc2'
down_revision: Union[str, Sequence[str], None] = '696a56e8234a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("wishlists", "favorites")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("favorites", "wishlists")
    # ### end Alembic commands ###
