"""add_createdAt_to_receipt

Revision ID: 2c6bb899f3bf
Revises: 3b7970d555e7
Create Date: 2026-06-29 23:05:36.303207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c6bb899f3bf'
down_revision: Union[str, Sequence[str], None] = '3b7970d555e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wishlists_id'), table_name='favorites')
    op.create_index(op.f('ix_favorites_id'), 'favorites', ['id'], unique=False)
    op.add_column('receipts', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receipts', 'created_at')
    op.drop_index(op.f('ix_favorites_id'), table_name='favorites')
    op.create_index(op.f('ix_wishlists_id'), 'favorites', ['id'], unique=False)
    # ### end Alembic commands ###
