"""empty message

Revision ID: 3910fd086731
Revises: b5bdcf18d9c7
Create Date: 2026-04-11 18:51:17.228324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3910fd086731'
down_revision: Union[str, Sequence[str], None] = 'b5bdcf18d9c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('reviews_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'reviews_count')
    # ### end Alembic commands ###
