"""empty message

Revision ID: 3bc500361a00
Revises: 3910fd086731
Create Date: 2026-04-12 17:44:15.458979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bc500361a00'
down_revision: Union[str, Sequence[str], None] = '3910fd086731'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_categories')
    op.alter_column('products', 'reviews_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('users', sa.Column('avatar', sa.String(length=1024), nullable=True))
    op.drop_column('users', 'avater')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avater', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    op.drop_column('users', 'avatar')
    op.alter_column('products', 'reviews_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_table('product_categories',
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('product_categories_category_id_fkey')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('product_categories_product_id_fkey')),
    sa.PrimaryKeyConstraint('product_id', 'category_id', name=op.f('product_categories_pkey'))
    )
    # ### end Alembic commands ###
