"""empty message

Revision ID: 6a13723f19a1
Revises: 3bc500361a00
Create Date: 2026-04-12 20:18:07.740254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a13723f19a1'
down_revision: Union[str, Sequence[str], None] = '3bc500361a00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_translations', sa.Column('category_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'product_translations', 'categories', ['category_id'], ['id'])
    op.drop_constraint(op.f('products_category_id_fkey'), 'products', type_='foreignkey')
    op.drop_column('products', 'category_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('products_category_id_fkey'), 'products', 'categories', ['category_id'], ['id'])
    op.drop_constraint(None, 'product_translations', type_='foreignkey')
    op.drop_column('product_translations', 'category_id')
    # ### end Alembic commands ###
