"""drop name and image columns from order_items

Revision ID: a14f75fa87bc
Revises: 3eda2badf698
Create Date: 2026-06-21 20:38:13.797045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a14f75fa87bc'
down_revision: Union[str, Sequence[str], None] = '3eda2badf698'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'image')
    op.drop_column('order_items', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('order_items', sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
