"""empty message

Revision ID: bde46413ea24
Revises: 9d51c180ddcf
Create Date: 2026-04-08 23:25:22.961435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bde46413ea24'
down_revision: Union[str, Sequence[str], None] = '9d51c180ddcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_categories',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('product_id', 'category_id')
    )
    op.create_unique_constraint(None, 'cart_items', ['cart_id', 'product_id'])
    op.create_unique_constraint(None, 'carts', ['user_id'])
    op.alter_column('order_items', 'receipt_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('order_items', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('order_items', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('order_items', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('payments', 'transaction_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.create_unique_constraint(None, 'wishlists', ['user_id', 'product_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wishlists', type_='unique')
    op.alter_column('payments', 'transaction_id',
               existing_type=sa.String(length=20),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('order_items', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('order_items', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('order_items', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('order_items', 'receipt_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'carts', type_='unique')
    op.drop_constraint(None, 'cart_items', type_='unique')
    op.drop_table('product_categories')
    # ### end Alembic commands ###
